__object__:
  path: generate
  name: AdversarialFlowGenerator

gen:
  model:
    __inherit__: configs/models/afm/dit/xl2.yaml
    use_t_src: True
    use_t_tgt: False
  checkpoint: xl2_2nfe_guided_FID2.11.pth
  pred_type: v

vae:
  model:
    __inherit__: configs/models/afm/dit/vae.yaml
  checkpoint: sd-vae-ft-mse.pth
  scaling_factor: 0.18215
  compile: True
  dtype: float32

generation:
  seed: 0
  steps: 2  # Change steps to match checkpoint.
  output: output/xl2_2nfe