__object__:
  path: generate
  name: AdversarialFlowGenerator

gen:
  model:
    __inherit__: configs/models/xl2.yaml
    use_t_src: True
    use_t_tgt: False
  checkpoint: xl2_4nfe_guided_FID2.03.pth
  pred_type: v

vae:
  model:
    __inherit__: configs/models/vae.yaml
  checkpoint: sd-vae-ft-mse.pth
  scaling_factor: 0.18215
  compile: True
  dtype: float32

generation:
  seed: 0
  steps: 4
  output: output/xl2_4nfe