__object__:
  path: train_continuous_adversarial_flow_imagenet
  name: ContinuousAdversarialFlowTrainer

exp:
  gen: xl2
  dis: xl2
  gpu: 8
  bsz: 256
  gen_lr: 1e-5
  dis_lr: 1e-5
  N: 16
  ot: 0.0
  warmup: 10000 # for bsz256, 5k is 1 epoch, 10k is 2 epochs.
  postfix: ""

data:
  train:
    dataset:
      path: configs.data.imagenet_offline
      resolution: 256
      flip_prob: 0.5
    dataloader:
      batch_size: ${eval:'${exp.bsz} // ${exp.gpu}'}
      num_workers: 8
      prefetch_factor: 32

gen:
  model:
    __inherit__: configs/models/cafm/sit/${exp.gen}.yaml
  checkpoint: ./SiT-XL-2-256.pt
  dropout: 0.1

dis:
  model:
    __inherit__: configs/models/cafm/sit/${exp.dis}.yaml
    __object__:
      path: models.cafm.sit.discriminator
      name: Discriminator
    norm_type: rms
  checkpoint: ./SiT-XL-2-256.pt
  strict: False

ema:
  decay: 0.99

vae:
  model:
    __inherit__: configs/models/cafm/sit/vae.yaml
  checkpoint: ./sd-vae-ft-mse.pth
  scaling_factor: 0.18215
  compile: True
  dtype: bfloat16

adversarial:
  N: ${exp.N}
  cp_scale: 0.001
  ot_scale: ${exp.ot}
  warmup: ${exp.warmup}

training:
  project: continuous-adversarial-flow-models
  name: sit-cafm-${exp.gen}${exp.dis}-b${exp.bsz}-lr${exp.gen_lr}-ot${exp.dis_lr}-ot${exp.ot}-N${exp.N}-warm${exp.warmup}${exp.postfix}
  seed: Null
  init_step: 0
  steps: 1_000_000       # For bsz256, 5k iter is 1 epoch. 50k is 10 epochs.
  timesteps: uniform
  gradient_clip: 10000.0
  dis_gradient_clip: 10000.0

optimizer:
  gen_lr: ${exp.gen_lr}
  dis_lr: ${exp.dis_lr}
  weight_decay: 0.0
  betas: [0.0, 0.95]

validation:
  enabled: True
  interval: 1000
  max_batch_size: 16
  steps: 250
  sampler: heun

writer:
  wandb:
    project: ${training.project}
    name: ${training.name}
    resume: "allow"
  interval:
    metrics: 100
    visuals: 500
  max_batch_size: 8

evaluation:
  interval: 50000
  metrics:
    fid:
      __object__:
        path: common.metrics
        name: FID
        args: as_params
      extractor_path: ./weights-inception-2015-12-05-6726825d.pth
      resolution: 299
      interpolation: bilinear
      target_info_path: ./openai_imagenet_train_info.pt
      normalize: True

persistence:
  interval: 25000
  override: True
  path: ./${training.project}/${training.name}